language: node_js
dist: trusty
sudo: required
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install -g yarn
  - yarn install
before_script:
  - yarn run lint
script:
  - xvfb-run yarn run test
